version: "2"

services:
  vote:
    build: ./vote
    command: python app.py
    depends_on:
      - redis    
    expose:
      - "80"

  redis:
    image: redis:alpine
    expose: ["6379"]
    depends_on:
      - worker

  worker:
    build: ./worker
    depends_on:
      - db

  db:
    image: postgres:9.4

  result:
    build: ./result
    command: nodemon --debug server.js
    expose:
      - "80"
    depends_on:
      - db
