version: "2"

services:
  vote:
    image: sebmoule/vote_vote
    command: python app.py
    depends_on:
      - redis    
    expose:
      - "80"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/vote"
      - "traefik.docker.network=traefik_net"   
    networks:
     - traefik_net
     - private       


  redis:
    image: redis:alpine
    expose: ["6379"]
    depends_on:
      - worker
    labels:
      - "traefik.enable=false"  
    networks:
     - private
     
  worker:
    image: sebmoule/vote_worker
    depends_on:
      - db
    labels:
      - "traefik.enable=false"  
    networks:
     - private      

  db:
    image: postgres:9.4
    labels:
      - "traefik.enable=false"  
    networks:
     - private
     
  result:
    image: sebmoule/vote_result
    command: nodemon --debug server.js
    expose:
      - "80"
    depends_on:
      - db
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/result"
      - "traefik.docker.network=traefik_net"   
    networks:
     - traefik_net
     - private       


networks:
  private:
  traefik_net:
    external: true
