version: "3"

services:
  vote:
    image: sebmoule/vote_vote
    command: python app.py
    depends_on:
      - redis    
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/vote/
        - com.df.port=80
    networks:
     - proxy_public
     - private       



  redis:
    image: redis:alpine
    depends_on:
      - worker
    deploy:
      labels:
        - com.df.notify=false
    networks:
     - private
     
  worker:
    image: sebmoule/vote_worker
    depends_on:
      - db
    deploy:
      replicas: 1
      labels:
        - com.df.notify=false
    networks:
     - private      

  db:
    image: postgres:9.4
    deploy:
      labels:
        - com.df.notify=false
    networks:
     - private
     
  result:
    image: sebmoule/vote_result
    command: nodemon --debug server.js
    depends_on:
      - db
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/result/
        - com.df.port=80
    networks:
     - proxy_public
     - private       


networks:
  private:
  proxy_public:
    external: true
